// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: demory/demory.proto

package demory

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinToClusterResponse_JoinResult int32

const (
	JoinToClusterResponse_SUCCESS      JoinToClusterResponse_JoinResult = 0
	JoinToClusterResponse_NOT_A_LEADER JoinToClusterResponse_JoinResult = 1
)

// Enum value maps for JoinToClusterResponse_JoinResult.
var (
	JoinToClusterResponse_JoinResult_name = map[int32]string{
		0: "SUCCESS",
		1: "NOT_A_LEADER",
	}
	JoinToClusterResponse_JoinResult_value = map[string]int32{
		"SUCCESS":      0,
		"NOT_A_LEADER": 1,
	}
)

func (x JoinToClusterResponse_JoinResult) Enum() *JoinToClusterResponse_JoinResult {
	p := new(JoinToClusterResponse_JoinResult)
	*p = x
	return p
}

func (x JoinToClusterResponse_JoinResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinToClusterResponse_JoinResult) Descriptor() protoreflect.EnumDescriptor {
	return file_demory_demory_proto_enumTypes[0].Descriptor()
}

func (JoinToClusterResponse_JoinResult) Type() protoreflect.EnumType {
	return &file_demory_demory_proto_enumTypes[0]
}

func (x JoinToClusterResponse_JoinResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinToClusterResponse_JoinResult.Descriptor instead.
func (JoinToClusterResponse_JoinResult) EnumDescriptor() ([]byte, []int) {
	return file_demory_demory_proto_rawDescGZIP(), []int{11, 0}
}

type MapPutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MapPutRequest) Reset() {
	*x = MapPutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demory_demory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapPutRequest) ProtoMessage() {}

func (x *MapPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demory_demory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapPutRequest.ProtoReflect.Descriptor instead.
func (*MapPutRequest) Descriptor() ([]byte, []int) {
	return file_demory_demory_proto_rawDescGZIP(), []int{0}
}

func (x *MapPutRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapPutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MapPutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type MapPutIfAbsentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MapPutIfAbsentRequest) Reset() {
	*x = MapPutIfAbsentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demory_demory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapPutIfAbsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapPutIfAbsentRequest) ProtoMessage() {}

func (x *MapPutIfAbsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demory_demory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapPutIfAbsentRequest.ProtoReflect.Descriptor instead.
func (*MapPutIfAbsentRequest) Descriptor() ([]byte, []int) {
	return file_demory_demory_proto_rawDescGZIP(), []int{1}
}

func (x *MapPutIfAbsentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapPutIfAbsentRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MapPutIfAbsentRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type MapGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *MapGetRequest) Reset() {
	*x = MapGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demory_demory_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapGetRequest) ProtoMessage() {}

func (x *MapGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demory_demory_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapGetRequest.ProtoReflect.Descriptor instead.
func (*MapGetRequest) Descriptor() ([]byte, []int) {
	return file_demory_demory_proto_rawDescGZIP(), []int{2}
}

func (x *MapGetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type MapGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MapGetResponse) Reset() {
	*x = MapGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demory_demory_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapGetResponse) ProtoMessage() {}

func (x *MapGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demory_demory_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapGetResponse.ProtoReflect.Descriptor instead.
func (*MapGetResponse) Descriptor() ([]byte, []int) {
	return file_demory_demory_proto_rawDescGZIP(), []int{3}
}

func (x *MapGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type MapRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *MapRemoveRequest) Reset() {
	*x = MapRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demory_demory_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapRemoveRequest) ProtoMessage() {}

func (x *MapRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demory_demory_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapRemoveRequest.ProtoReflect.Descriptor instead.
func (*MapRemoveRequest) Descriptor() ([]byte, []int) {
	return file_demory_demory_proto_rawDescGZIP(), []int{4}
}

func (x *MapRemoveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapRemoveRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type MapClearRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *MapClearRequest) Reset() {
	*x = MapClearRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demory_demory_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapClearRequest) ProtoMessage() {}

func (x *MapClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demory_demory_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapClearRequest.ProtoReflect.Descriptor instead.
func (*MapClearRequest) Descriptor() ([]byte, []int) {
	return file_demory_demory_proto_rawDescGZIP(), []int{5}
}

func (x *MapClearRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapClearRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CacheGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CacheGetRequest) Reset() {
	*x = CacheGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demory_demory_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetRequest) ProtoMessage() {}

func (x *CacheGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demory_demory_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetRequest.ProtoReflect.Descriptor instead.
func (*CacheGetRequest) Descriptor() ([]byte, []int) {
	return file_demory_demory_proto_rawDescGZIP(), []int{6}
}

func (x *CacheGetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CacheGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CacheGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CacheGetResponse) Reset() {
	*x = CacheGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demory_demory_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetResponse) ProtoMessage() {}

func (x *CacheGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demory_demory_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetResponse.ProtoReflect.Descriptor instead.
func (*CacheGetResponse) Descriptor() ([]byte, []int) {
	return file_demory_demory_proto_rawDescGZIP(), []int{7}
}

func (x *CacheGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CacheRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CacheRemoveRequest) Reset() {
	*x = CacheRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demory_demory_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRemoveRequest) ProtoMessage() {}

func (x *CacheRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demory_demory_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRemoveRequest.ProtoReflect.Descriptor instead.
func (*CacheRemoveRequest) Descriptor() ([]byte, []int) {
	return file_demory_demory_proto_rawDescGZIP(), []int{8}
}

func (x *CacheRemoveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CacheRemoveRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CacheClearRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CacheClearRequest) Reset() {
	*x = CacheClearRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demory_demory_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheClearRequest) ProtoMessage() {}

func (x *CacheClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demory_demory_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheClearRequest.ProtoReflect.Descriptor instead.
func (*CacheClearRequest) Descriptor() ([]byte, []int) {
	return file_demory_demory_proto_rawDescGZIP(), []int{9}
}

func (x *CacheClearRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CacheClearRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CachePutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CachePutRequest) Reset() {
	*x = CachePutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demory_demory_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CachePutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachePutRequest) ProtoMessage() {}

func (x *CachePutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demory_demory_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachePutRequest.ProtoReflect.Descriptor instead.
func (*CachePutRequest) Descriptor() ([]byte, []int) {
	return file_demory_demory_proto_rawDescGZIP(), []int{10}
}

func (x *CachePutRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CachePutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CachePutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type JoinToClusterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result JoinToClusterResponse_JoinResult `protobuf:"varint,1,opt,name=result,proto3,enum=JoinToClusterResponse_JoinResult" json:"result,omitempty"`
}

func (x *JoinToClusterResponse) Reset() {
	*x = JoinToClusterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demory_demory_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinToClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToClusterResponse) ProtoMessage() {}

func (x *JoinToClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demory_demory_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToClusterResponse.ProtoReflect.Descriptor instead.
func (*JoinToClusterResponse) Descriptor() ([]byte, []int) {
	return file_demory_demory_proto_rawDescGZIP(), []int{11}
}

func (x *JoinToClusterResponse) GetResult() JoinToClusterResponse_JoinResult {
	if x != nil {
		return x.Result
	}
	return JoinToClusterResponse_SUCCESS
}

type JoinToClusterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerAddress string `protobuf:"bytes,1,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	ServerId      string `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	PreviousIndex uint64 `protobuf:"varint,3,opt,name=previous_index,json=previousIndex,proto3" json:"previous_index,omitempty"`
}

func (x *JoinToClusterRequest) Reset() {
	*x = JoinToClusterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demory_demory_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinToClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToClusterRequest) ProtoMessage() {}

func (x *JoinToClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demory_demory_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToClusterRequest.ProtoReflect.Descriptor instead.
func (*JoinToClusterRequest) Descriptor() ([]byte, []int) {
	return file_demory_demory_proto_rawDescGZIP(), []int{12}
}

func (x *JoinToClusterRequest) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *JoinToClusterRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *JoinToClusterRequest) GetPreviousIndex() uint64 {
	if x != nil {
		return x.PreviousIndex
	}
	return 0
}

var File_demory_demory_proto protoreflect.FileDescriptor

var file_demory_demory_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x0d, 0x4d, 0x61, 0x70, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x53, 0x0a, 0x15, 0x4d, 0x61, 0x70, 0x50, 0x75, 0x74, 0x49, 0x66, 0x41, 0x62, 0x73, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x35, 0x0a, 0x0d, 0x4d, 0x61, 0x70, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x26, 0x0a, 0x0e, 0x4d,
	0x61, 0x70, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x38, 0x0a, 0x10, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x37, 0x0a,
	0x0f, 0x4d, 0x61, 0x70, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x37, 0x0a, 0x0f, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x28, 0x0a, 0x10, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3a, 0x0a, 0x12, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x39, 0x0a, 0x11, 0x43, 0x61, 0x63, 0x68, 0x65, 0x43, 0x6c,
	0x65, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x4d, 0x0a, 0x0f, 0x43, 0x61, 0x63, 0x68, 0x65, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x7f, 0x0a, 0x15, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x54,
	0x6f, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x2b, 0x0a, 0x0a, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x10,
	0x0a, 0x0c, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x5f, 0x4c, 0x45, 0x41, 0x44, 0x45, 0x52, 0x10, 0x01,
	0x22, 0x81, 0x01, 0x0a, 0x14, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a,
	0x0e, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x32, 0xc6, 0x04, 0x0a, 0x06, 0x44, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12,
	0x32, 0x0a, 0x06, 0x4d, 0x61, 0x70, 0x50, 0x75, 0x74, 0x12, 0x0e, 0x2e, 0x4d, 0x61, 0x70, 0x50,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x06, 0x4d, 0x61, 0x70, 0x47, 0x65, 0x74, 0x12, 0x0e, 0x2e,
	0x4d, 0x61, 0x70, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e,
	0x4d, 0x61, 0x70, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x42, 0x0a, 0x0e, 0x4d, 0x61, 0x70, 0x50, 0x75, 0x74, 0x49, 0x66, 0x41, 0x62, 0x73, 0x65,
	0x6e, 0x74, 0x12, 0x16, 0x2e, 0x4d, 0x61, 0x70, 0x50, 0x75, 0x74, 0x49, 0x66, 0x41, 0x62, 0x73,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x09, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x12, 0x11, 0x2e, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x36,
	0x0a, 0x08, 0x4d, 0x61, 0x70, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x12, 0x10, 0x2e, 0x4d, 0x61, 0x70,
	0x43, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x08, 0x43, 0x61, 0x63, 0x68, 0x65, 0x50,
	0x75, 0x74, 0x12, 0x10, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x31,
	0x0a, 0x08, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x12, 0x10, 0x2e, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3c, 0x0a, 0x0b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x12, 0x13, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x3a, 0x0a, 0x0a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x12, 0x12, 0x2e,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x4a,
	0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x4a,
	0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x34, 0x5a,
	0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x75, 0x73, 0x65,
	0x79, 0x69, 0x6e, 0x62, 0x61, 0x62, 0x61, 0x6c, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x2d,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x64, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_demory_demory_proto_rawDescOnce sync.Once
	file_demory_demory_proto_rawDescData = file_demory_demory_proto_rawDesc
)

func file_demory_demory_proto_rawDescGZIP() []byte {
	file_demory_demory_proto_rawDescOnce.Do(func() {
		file_demory_demory_proto_rawDescData = protoimpl.X.CompressGZIP(file_demory_demory_proto_rawDescData)
	})
	return file_demory_demory_proto_rawDescData
}

var file_demory_demory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_demory_demory_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_demory_demory_proto_goTypes = []interface{}{
	(JoinToClusterResponse_JoinResult)(0), // 0: JoinToClusterResponse.JoinResult
	(*MapPutRequest)(nil),                 // 1: MapPutRequest
	(*MapPutIfAbsentRequest)(nil),         // 2: MapPutIfAbsentRequest
	(*MapGetRequest)(nil),                 // 3: MapGetRequest
	(*MapGetResponse)(nil),                // 4: MapGetResponse
	(*MapRemoveRequest)(nil),              // 5: MapRemoveRequest
	(*MapClearRequest)(nil),               // 6: MapClearRequest
	(*CacheGetRequest)(nil),               // 7: CacheGetRequest
	(*CacheGetResponse)(nil),              // 8: CacheGetResponse
	(*CacheRemoveRequest)(nil),            // 9: CacheRemoveRequest
	(*CacheClearRequest)(nil),             // 10: CacheClearRequest
	(*CachePutRequest)(nil),               // 11: CachePutRequest
	(*JoinToClusterResponse)(nil),         // 12: JoinToClusterResponse
	(*JoinToClusterRequest)(nil),          // 13: JoinToClusterRequest
	(*empty.Empty)(nil),                   // 14: google.protobuf.Empty
}
var file_demory_demory_proto_depIdxs = []int32{
	0,  // 0: JoinToClusterResponse.result:type_name -> JoinToClusterResponse.JoinResult
	1,  // 1: Demory.MapPut:input_type -> MapPutRequest
	3,  // 2: Demory.MapGet:input_type -> MapGetRequest
	2,  // 3: Demory.MapPutIfAbsent:input_type -> MapPutIfAbsentRequest
	5,  // 4: Demory.MapRemove:input_type -> MapRemoveRequest
	6,  // 5: Demory.MapClear:input_type -> MapClearRequest
	11, // 6: Demory.CachePut:input_type -> CachePutRequest
	7,  // 7: Demory.CacheGet:input_type -> CacheGetRequest
	9,  // 8: Demory.CacheRemove:input_type -> CacheRemoveRequest
	10, // 9: Demory.CacheClear:input_type -> CacheClearRequest
	13, // 10: Demory.JoinToCluster:input_type -> JoinToClusterRequest
	14, // 11: Demory.MapPut:output_type -> google.protobuf.Empty
	4,  // 12: Demory.MapGet:output_type -> MapGetResponse
	14, // 13: Demory.MapPutIfAbsent:output_type -> google.protobuf.Empty
	14, // 14: Demory.MapRemove:output_type -> google.protobuf.Empty
	14, // 15: Demory.MapClear:output_type -> google.protobuf.Empty
	14, // 16: Demory.CachePut:output_type -> google.protobuf.Empty
	8,  // 17: Demory.CacheGet:output_type -> CacheGetResponse
	14, // 18: Demory.CacheRemove:output_type -> google.protobuf.Empty
	14, // 19: Demory.CacheClear:output_type -> google.protobuf.Empty
	12, // 20: Demory.JoinToCluster:output_type -> JoinToClusterResponse
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_demory_demory_proto_init() }
func file_demory_demory_proto_init() {
	if File_demory_demory_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_demory_demory_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapPutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demory_demory_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapPutIfAbsentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demory_demory_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demory_demory_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demory_demory_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demory_demory_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapClearRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demory_demory_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demory_demory_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demory_demory_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demory_demory_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CacheClearRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demory_demory_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CachePutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demory_demory_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinToClusterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demory_demory_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinToClusterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_demory_demory_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demory_demory_proto_goTypes,
		DependencyIndexes: file_demory_demory_proto_depIdxs,
		EnumInfos:         file_demory_demory_proto_enumTypes,
		MessageInfos:      file_demory_demory_proto_msgTypes,
	}.Build()
	File_demory_demory_proto = out.File
	file_demory_demory_proto_rawDesc = nil
	file_demory_demory_proto_goTypes = nil
	file_demory_demory_proto_depIdxs = nil
}
